language: go
go:
  # - 1.6.x
  # - 1.7.x
  # - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

sudo: false

before_install:
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get -u github.com/mattn/go-isatty
  - go get -u github.com/axw/gocov/gocov
  - go get -u github.com/mattn/goveralls

script:
  - go run pinyin/main.go abc
  - go run pinyin/main.go -s Normal abc
  - echo "abc" | go run pinyin/main.go
  - echo "abc" > abc.txt && go run pinyin/main.go < abc.txt
  # - $HOME/gopath/bin/goveralls -service=travis-ci -v -package .
